In [ ]:
%pip install -U yfinance pandas beautifulsoup4 requests
%pip install "transformers==4.44.2" "torch==2.5.1"

In [20]:
import yfinance as yf
import pandas as pd
from pprint import pprint
import requests
from bs4 import BeautifulSoup
import torch
import transformers
from transformers import pipeline
from transformers.utils import is_torch_available

In [21]:
search = yf.Search("AAPL") # Default gives us 8 articles
news = search.news

pprint(news[0])

df = pd.DataFrame(news)
display(df)

{'link': 'https://finance.yahoo.com/markets/stocks/articles/prediction-alphabet-larger-company-apple-232900856.html',
 'providerPublishTime': 1792193340,
 'publisher': 'Motley Fool',
 'relatedTickers': ['GOOG', 'AAPL', 'NVDA'],
 'thumbnail': {'resolutions': [{'height': 738,
                                'tag': 'original',
                                'url': 'https://media.zenfs.com/en/motleyfool.com/2a198da898e1e63c86ca12813bd2ad3a.jpg',
                                'width': 1400},
                               {'height': 140,
                                'tag': '140x140',
                                'url': 'https://s.yimg.com/lo/mysterio/api/5585041C3E4A9AE48999B8DB1B4500B8496044DF9A1E83D6972D50082B2BDB47/subgraphmysterio/resizefill_w140_h140/https:%2F%2Fmedia.zenfs.com%2Fen%2Fmotleyfool.com%2F2a198da898e1e63c86ca12813bd2ad3a.jpg',
                                'width': 140}]},
 'title': 'Prediction: Alphabet Will Be a Larger Company Than Apple by the End '
          'of 2027',
 'type': 'STORY',
 'uuid': '5e0035d1-847e-3a79-aa14-fedb45395bf8'}

,uuid,title,publisher,link,providerPublishTime,type,thumbnail,relatedTickers
0,5e0035d1-847e-3a79-aa14-fedb45395bf8,Prediction: Alphabet Will Be a Larger Company ...,Motley Fool,https://finance.yahoo.com/markets/stocks/artic...,1792193340,STORY,{'resolutions': [{'url': 'https://media.zenfs....,"[GOOG, AAPL, NVDA]"
1,12a19546-b691-38fd-8a92-0a88758f06ef,Market Chatter: Apple Appoints Former Meta Exe...,MT Newswires,https://finance.yahoo.com/markets/stocks/artic...,1792191371,STORY,NaN,"[AAPL, META]"
2,596af860-67ee-3c68-a208-bfcfadf6a215,Taiwan Semiconductor Posts Record Q3 Results: ...,Zacks,https://finance.yahoo.com/markets/stocks/artic...,1792190160,STORY,{'resolutions': [{'url': 'https://media.zenfs....,"[TSM, TSM, AAPL, AMD, NVDA]"
3,c7e028b0-c8b5-3c35-8f5a-5a3b70d23374,Nasdaq 100 Records Worst Week In 18 Months As ...,Stocktwits,https://finance.yahoo.com/markets/stocks/artic...,1792188934,STORY,{'resolutions': [{'url': 'https://media.zenfs....,"[^GSPC, ^NDX, ^DJI, CRWV, ^RUT, SPY, DIA, IVZ,..."
4,4bb318f2-4454-3ac1-90a4-ce812b615d44,"Stock Market Today, Oct. 16: Apple Edges Highe...",Motley Fool,https://finance.yahoo.com/markets/stocks/artic...,1792187374,STORY,{'resolutions': [{'url': 'https://media.zenfs....,"[AAPL, MSFT, GOOG, ^IXIC, ^GSPC]"
5,bd9f3ace-7f96-34b1-b613-16c089d8198c,Tech Stocks Zig—and Apple Zags,The Wall Street Journal,https://finance.yahoo.com/m/bd9f3ace-7f96-34b1...,1792185614,STORY,{'resolutions': [{'url': 'https://media.zenfs....,"[AAPL, NVDA]"
6,5ee6712d-21f3-3b4b-aea1-531b69d766b5,This is the Cheapest Mag 7 Stock Right Now,Zacks,https://finance.yahoo.com/markets/stocks/artic...,1792184820,STORY,{'resolutions': [{'url': 'https://media.zenfs....,"[AMZN, TSLA, AAPL, BRK-B, GOOG]"
7,990d1896-43cd-3349-9be5-9dc32bf5f450,Apple's Next Legal Risk Could Reach $40 Billion,GuruFocus.com,https://finance.yahoo.com/technology/articles/...,1792183989,STORY,NaN,[AAPL]

In [22]:
article = news[0]
content = article.get("content", article)

url = (content.get("canonicalUrl") or {}).get("url") or content.get("link")

print("URL:", url)

# Download article HTML
response = requests.get(
    url,
    headers={"User-Agent": "Mozilla/5.0"},
    timeout=15
)
response.raise_for_status()

# Parse HTML
soup = BeautifulSoup(response.text, "html.parser")

# Locate main article
article_html = soup.find("article")

# Extract paragraphs
if article_html:
    paragraphs = article_html.find_all("p")
    full_text = "\n\n".join(
        p.get_text(" ", strip=True)
        for p in paragraphs
    )
else:
    full_text = None

# Display results
print("\nTITLE:")
print(content.get("title"))

print("\nFULL ARTICLE:")
print(full_text)

URL: https://finance.yahoo.com/markets/stocks/articles/prediction-alphabet-larger-company-apple-232900856.html

TITLE:
Prediction: Alphabet Will Be a Larger Company Than Apple by the End of 2027

FULL ARTICLE:
The above button links to Coinbase. Yahoo Finance is not a broker-dealer or investment adviser and does not offer securities or cryptocurrencies for sale or facilitate trading. Coinbase pays us for certain activity generated through this link. Prices displayed are informational.

Right now, Apple (NASDAQ: AAPL) and Alphabet (NASDAQ: GOOG) (NASDAQ: GOOGL) are the world's second- and third-largest companies, respectively. Apple's market cap sits just under $5 billion, while Alphabet's is $4.2 billion. While that's not an insignificant gap, I think Alphabet could close it over the next year and claim the title of the world's second-largest company.

It won't be easy, but I think there are two fronts where Alphabet can make up ground.

Missed Nvidia in 2009? This Rare Signal Is Flashing Again. In 2009, a "Double Down" signal flashed for a little-known chipmaker called Nvidia. For the first time in years, that same "Total Conviction" signal is flashing for a company 1/100th the size of Nvidia. Continue »

Apple and Alphabet are taking two completely different approaches to artificial intelligence . Apple really hasn't spent a whole lot on data centers or large language models, and has done almost nothing to develop its AI computing capabilities. In fact, it's planning to integrate Google Gemini into most of its products rather than spending heavily to develop its own AI model. While this may prove to be a genius strategy on Apple's part, it will limit its offerings to what Gemini is capable of.

Furthermore, Apple's AI features have been a bit lackluster. It has yet to launch a subscription AI service, and the next-generation Siri AI assistant was just launched with iOS 27. Time will tell how this pans out, but one thing is for certain: Apple is not going all in on AI.

But that may be its selling point as an investment.

At this point, it's the only big tech stock that isn't all-in on AI. As a result, it has become a bit of a safe-haven option for tech investors who want a hedge against AI exposure. As investors start to realize the payoffs and benefits of heavy AI investment , I think the sentiment that makes that desirable will change, but it explains why Apple stock has been so resilient over the past few months.

If this sentiment starts to shift in 2027, then Apple may not remain as attractive a stock as it is, as it's not growing all that fast.

GOOG Revenue (Quarterly YoY Growth) data by YCharts.

With Alphabet growing a fair bit faster than Apple, I think investors will start to realize how big of a deal AI is, and shift funds away from Apple.

Relative to Alphabet, Apple is priced at a premium. To compare them, I'll use the price-to-operating-earnings ratio. It's the better metric right now because Alphabet's standard P/E metric has been skewed by the huge gains it has accrued from its investments in Space Exploration Technologies (NASDAQ: SPCX) and Anthropic. Going a bit further up the financial sheet to focus on operating income factors the impact of those investments out of the equation, measuring the two based on their earnings from their actual businesses.

In the middle of this year, the companies were fairly in sync in terms of valuation. But a modest divergence has emerged. If they traded at the same valuation, Apple would still be slightly larger than Alphabet. Still, with Alphabet expected to grow much more quickly between now and the end of 2027, it will easily have higher operating income than Apple by then.

If Alphabet overtakes Apple in operating income generation, and if its valuation adjusts as the market takes a more positive view of the AI sector, I think Alphabet will overtake Apple in 2027 to become the world's second-largest company. To do this, it will likely need to deliver market-beating returns en route to a new all-time high, making Alphabet a great stock to buy now.

Before you buy stock in Alphabet, consider this:

The Motley Fool Stock Advisor analyst team just identified what they believe are the 10 best stocks for investors to buy now… and Alphabet wasn't one of them. The 10 stocks that made the cut could produce monster returns in the coming years.

Consider when Netflix made this list on December 17, 2004... if you invested $1,000 at the time of our recommendation, you'd have $391,581 !* Or when Nvidia made this list on April 15, 2005... if you invested $1,000 at the time of our recommendation, you'd have $1,334,780 !*

Now, it's worth noting Stock Advisor's total average return is 936% — a market-crushing outperformance compared to 213% for the S&P 500. Don't miss the latest top 10 list, available with Stock Advisor , and join an investing community built by individual investors for individual investors.

See the 10 stocks »

*Stock Advisor returns as of October 16, 2026.

Keithen Drury has positions in Alphabet. The Motley Fool has positions in and recommends Alphabet and Apple. The Motley Fool has a disclosure policy .

Prediction: Alphabet Will Be a Larger Company Than Apple by the End of 2027 was originally published by The Motley Fool

In [23]:
# Sentiment Analysis Experiment (Unstructured -> Structured Data)

import os
os.environ["USE_TF"] = "0"

import pandas as pd
import matplotlib.pyplot as plt
from transformers import pipeline

sentiment = pipeline(
    "text-classification",
    model="ProsusAI/finbert",
    framework="pt",
    device="cpu"
)

if full_text and full_text.strip():

    results = sentiment(
        full_text,
        truncation=True,
        top_k=None
    )

    for result in results:
        print(result["label"], result["score"])

    df_sentiment = pd.DataFrame(results)

    display(df_sentiment)

else:
    print("No article text available.")

/opt/anaconda3/lib/python3.12/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

neutral 0.8835909962654114
positive 0.08149680495262146
negative 0.034912239760160446

      label     score
0   neutral  0.883591
1  positive  0.081497
2  negative  0.034912